image: ubuntu/lts
packages:
  # Dependencies to compile cpython
  - build-essential
  - curl
  - libreadline-dev
  - libbz2-dev 
  - libffi-dev
  - liblzma-dev
  - libncursesw5-dev
  - libsqlite3-dev
  - libssl-dev
  - libxml2-dev
  - libxmlsec1-dev
  - make
  - wget
  - xz-utils
  - zlib1g-dev
  
secrets:
  - 98889dd3-6e0f-4b6d-ae3c-78d13f59fb7e

sources:
  - https://git.sr.ht/~amirouche/asyncio-foundationdb

tasks:
  - foundationdb: |
      cd asyncio-foundationdb
      sudo make init-foundationdb
  - cpython-37: |
      export PATH=$HOME/.local/bin:$PATH
      cd asyncio-foundationdb
      rm -rf .venv
      ./python.sh 3.7
      echo "exit()" | sh venv python3.7
      ./venv pip install poetry
      ./venv make init
      ./venv make check
      # Publish if there is tag on the current commit
      set +x
      git describe --tags HEAD && ./venv poetry config http-basic.pypi __token__ $(cat ~/.pypi-token) || true
      set -x
      git describe --tags HEAD && ./venv poetry build || true
      git describe --tags HEAD && ./venv poetry publish || true
      
  #     compile-python 3.8.12
  #     compile-python 3.9.9
  #     compile-python 3.10.1
  #     compile-python 3.11.0 a3
  # - 
