sudo: required
language: python
cache: pip
install: make init

jobs:
  include:
    - stage: test
      python: '3.5'
      script:
        - make check
    - stage: test
      python: '3.6'
      script:
        - make check
    - stage: test
      sudo: true
      dist: xenial
      python: '3.7'
      script:
        - make check


after_success:
  - make check-coverage
  - codecov
