#!/bin/bash

#
# tl;dr: use or create a virtual environment.
#
# If there is no directory called .venv, create a virtual
# environment called .venv, install dependencies from requirements.txt
# and spawn a new shell inside that venv. The Python version used to
# create the venv can be passed as first argument.
#
# Otherwise spawn a new shell for the virtualenv .venv, possibly run
# the provided command: ./venv ipython
#
# TODO: investigate https://github.com/berdario/pew
#

set -e

PYTHON=$1

if [ "$PYTHON" = "" ]; then
    PYTHON="python3"
fi;

if test -d .venv; then
    if [[ -z "$MYVENV" ]]; then
        export MYVENV=1
        source .venv/bin/activate
        if [[ -z "$@" ]]; then
            if test -f .venv/bin/rc.sh; then
                bash --rcfile .venv/bin/rc.sh
            else
                bash --norc --noprofile
            fi
        else
            exec "$@"
        fi
    else
        echo "You are already in a virtual environment!"
    fi
else
    $PYTHON -m venv --prompt="$(basename $(pwd))" .venv
    curl -sSL https://bootstrap.pypa.io/get-pip.py -o get-pip.py
    ./venv python get-pip.py
    rm -r get-pip.py
    ./venv pip install --quiet poetry
    ./venv poetry install --quiet
    echo VENV_PATH=$(pwd) > .venv/bin/rc.sh
    cat .venv/bin/activate >> .venv/bin/rc.sh
    ./venv "$@"
fi
