name: Binding Tester (reusable)

on:
  workflow_call:
    inputs:
      iterations:
        required: true
        type: number

env:
  GH_TOKEN: ${{ github.token }}
  GIT_OBJECT: ${{ github.head_ref || github.ref_name }}

jobs:
  binding-tester:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: "3.9"
            python_gil: "1"
          - python-version: "3.10"
            python_gil: "1"
          - python-version: "3.11"
            python_gil: "1"
          - python-version: "3.12"
            python_gil: "1"
          - python-version: "3.13"
            python_gil: "1"
          - python-version: "3.14"
            python_gil: "1"
          - python-version: "3.14t"
            python_gil: "0"
          - python-version: "pypy-3.9"
            python_gil: "1"
          - python-version: "pypy-3.10"
            python_gil: "1"
          - python-version: "pypy-3.11"
            python_gil: "1"
    env:
      PYTHON_GIL: ${{ matrix.python_gil }}
    name: Binding Tester (Python ${{ matrix.python-version }})
    steps:
      - run: gh repo clone amirouche/asyncio-foundationdb -- found
      - run: cd found && git checkout $GIT_OBJECT

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - run: python --version

      - name: Install FoundationDB
        run: cd found && sudo make debian

      - name: Enable tenants
        run: fdbcli --exec "configure tenant_mode=optional_experimental"

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip > /dev/null
          pip install uv
          cd found && make init

      - name: Run correctness suite
        run: cd found && make check-correctness ITERATIONS=${{ inputs.iterations }}
