name: Binding Tester (reusable)

on:
  workflow_call:
    inputs:
      iterations:
        required: true
        type: number

env:
  GH_TOKEN: ${{ github.token }}
  GIT_OBJECT: ${{ github.head_ref || github.ref_name }}
  PYTHON_GIL: "0"

jobs:
  binding-tester:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"
          - "3.14t"
          - "pypy-3.9"
          - "pypy-3.10"
          - "pypy-3.11"
    name: Binding Tester (Python ${{ matrix.python-version }})
    steps:
      - run: gh repo clone amirouche/asyncio-foundationdb -- found
      - run: cd found && git checkout $GIT_OBJECT

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - run: python --version

      - name: Install FoundationDB
        run: cd found && sudo make debian

      - name: Enable tenants
        run: fdbcli --exec "configure tenant_mode=optional_experimental"

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip > /dev/null
          pip install uv
          cd found && make init

      - name: Run correctness suite
        run: cd found && make check-correctness ITERATIONS=${{ inputs.iterations }}
