name: Build

on: workflow_dispatch

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
     fail-fast: false
     matrix:
        os: [ubuntu-22.04, windows-2019, macOS-11]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v3

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.16.2

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_TEST_COMMAND: make check
          CIBW_BEFORE_ALL: sudo apt install wget && sudo make debian

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
