name: Continuous Integration

on:
    push:

env:
  GH_TOKEN: ${{ github.token }}
  GIT_OBJECT: ${{ github.head_ref || github.ref_name }}

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: "3.9"
            os: ubuntu-latest
            python_gil: "1"
          - python-version: "3.10"
            os: ubuntu-latest
            python_gil: "1"
          - python-version: "3.11"
            os: ubuntu-latest
            python_gil: "1"
          - python-version: "3.12"
            os: ubuntu-latest
            python_gil: "1"
          - python-version: "3.13"
            os: ubuntu-latest
            python_gil: "1"
          - python-version: "3.14"
            os: ubuntu-latest
            python_gil: "1"
          - python-version: "3.14t"
            os: ubuntu-latest
            python_gil: "0"
          - python-version: "pypy-3.9"
            os: ubuntu-latest
            python_gil: "1"
          - python-version: "pypy-3.10"
            os: ubuntu-latest
            python_gil: "1"
          - python-version: "pypy-3.11"
            os: ubuntu-latest
            python_gil: "1"
    env:
      PYTHON_GIL: ${{ matrix.python_gil }}
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.python-version }} on ${{ matrix.os }}
    steps:
      - run: gh repo clone amirouche/asyncio-foundationdb -- found
      - run: cd found && git checkout $GIT_OBJECT
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
           python-version: ${{ matrix.python-version }}
           architecture: x64
      - run: python --version
      - run: cd found && sudo make debian
      - run: python3 -m pip install --upgrade pip > /dev/null
      - run: pip install uv
      - run: cd found && make init
      - run: cd found && uv run python readme.py
      - run: cd found && make check
