name: Continuous Integration

on:
    push:

jobs:
  checks:
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - 3.9
          - "3.10"
          - "3.11"
          - "3.12"
          - pypy-3.8
          - pypy-3.9
        os:
          - ubuntu-latest
    runs-on:  ${{ matrix.os }}
    name: ${{ matrix.python-version }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
           python-version: ${{ matrix.python-version }}
           architecture: x64
      - run: sudo make init-foundationdb
      - run: pip install --upgrade pip
      - run: pip install poetry
      - run: ./venv python3
      - run: ./venv make init
      - run: ./venv make check
