name: Scheduled correctness

on:
  workflow_dispatch:
  # https://crontab.guru/#0_2_*_*_*
  # "At 02:00." — every day
  schedule:
    - cron: "0 2 * * *"

jobs:
  binding-tester:
    if: github.repository == 'amirouche/asyncio-foundationdb'
    uses: ./.github/workflows/_binding-tester.yaml
    with:
      iterations: 300
