name: PR correctness

on:
  workflow_dispatch:
  pull_request:
    types: [ labeled, unlabeled, opened, synchronize, reopened ]

jobs:
  binding-tester:
    if: contains(github.event.pull_request.labels.*.name, 'correctness')
    uses: ./.github/workflows/_binding-tester.yaml
    with:
      iterations: 1000
