name: release

on: workflow_dispatch


env:
  BRANCH: ${{ github.head_ref || github.ref_name }}

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - run: gh repo clone amirouche/asyncio-foundationdb -- --branch $BRANCH --depth 1
      - run: cd cli && git fetch --tags
      - run: cd cli && gh release create --draft $(git tag --points-at HEAD)

  check-build-release:
    strategy:
      fail-fast: true
      matrix:
        python-version:
          - 3.9
          - "3.10"
          - "3.11"
          # - "3.12" # it is still early, first released 2023-09-19.
          - pypy-3.8
          - pypy-3.9
        os:
          - ubuntu-latest

    runs-on:  ${{ matrix.os }}
    name: ${{ matrix.python-version }} on ${{ matrix.os }}
    needs: create-release
    steps:
      - run: gh repo clone amirouche/asyncio-foundationdb -- --branch $BRANCH --depth 1
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
           python-version: ${{ matrix.python-version }}
           architecture: x64
      - run: python --version
      - run: sudo make init-foundationdb
      - run: pip install --upgrade pip
      - run: pip install poetry
      - run: ./venv python
      - run: ./venv make init
      - run: ./venv make check
      - run: ./venv poetry config pypi-token.pypi ${{ secrets.PYPI_ASYNCIO_FOUNDATIONDB }}
      - run: ./venv poetry release --build
