name: Release

on: workflow_dispatch

env:
  GH_TOKEN: ${{ github.token }}
  GIT_OBJECT: ${{ github.head_ref || github.ref_name }}

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - 3.8
          - 3.9
          - "3.10"
          - "3.11"
          - "pypy-3.8"
          - "pypy-3.9"
          - "pypy-3.10"
        os:
          - ubuntu-latest
    runs-on:  ${{ matrix.os }}
    name: ${{ matrix.python-version }} on ${{ matrix.os }}
    steps:
      - run: gh repo clone amirouche/asyncio-foundationdb -- found
      - run: cd found && git checkout $GIT_OBJECT
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
           python-version: ${{ matrix.python-version }}
           architecture: x64
      - run: python --version
      - run: cd found && sudo make debian
      - run: pip install --upgrade pip
      - run: pip install poetry
      - run: cd found && make init
      - run: cd found && poetry run python readme.py
      - run: cd found && poetry run make check
      - run: poetry config pypi-token.pypi ${{ secrets.PYPI }}
      - run: cd found && poetry publish --build --skip-existing
